@startuml SHOW_PERSON_PORTRAIT() Saude Online - Contexto
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()

title <size:18>Diagrama de Contexto do Sistema</size>\n<size:11>Diagrama de contexto do sistema Saúde Online</size>

Person(app_user, "Usuário", "Paciente que usa o App e está sendo monitorado")
System(app_system,"Saúde Online", "Monitora a saude do usuário, além de outras funcionalidades")
'System(app_system,"Saúde Online", "Monitora o usuário, entra em contato em caso de emergência, além de outras funcionalidades")
System_Ext(clinic_system,"Sistema da clínica", "Gerencia as informações da clínica e dos pacientes")

app_user ..> app_system: Acessa a aplicação
app_system ..> clinic_system: Envia requisições
clinic_system ..> app_system: Recebe informações solicitadas 
@enduml